### ISSUE TITLE
Update Action Alert Now tab under  Take Action

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#108]
Action Alert in top position should be the alert highlighted in the sliding banner on the home page: Let your state Senator and Representative know why you support ranked choice voting

**Comment by miketbrand** [comment]
@hwasserstrum, what do you mean by "highlighted"?

**Comment by hwasserstrum** [comment]
I looked at this last night and thought I might do better this morning, but alas I still don't know what was on my mind when I wrote this. Sorry. The sliding banner on the home page now has 3 items: the action alert to tell your elected officials why you like RCV, the reasons you like RCV, and a poll of your favorite Republican presidential candidates. The first two are still good. The 3rd should be replaced. Ideally, the most recent action alert should be 1 of the 3 but our most recent action alert is no longer appropriate. I just added an event to work the polls on primary election day and that could go up now in its place. You can ask John Thomson for a good graphic or use vote 4.jpg on our Google Drive.
That item will have to be revised on March 6 to work the polls on primary runoff date with a link to a new event.
What is the best way for someone adding a tech project to let you know the priority? Indicate it in the GitHub issue or send you a separate email? My top priority now is a really quick one to add Rep. Crenshaw's endorsement which I see you just assigned to yourself.ThanksHarriet
    On Wednesday, February 14, 2024 at 07:33:45 PM CST, Michael Brand ***@***.***> wrote:  
 
 


@hwasserstrum, what do you mean by "highlighted"?

**Comment by miketbrand** [comment]
@hwasserstrum ,

I've made the image switch.  Let me know what you think.

I would recommend just including the priority of any new tasks in the affiliated Git issue.

**Comment by hwasserstrum** [comment]
Can you please put the item you added in the first position so all viewers see it regardless of how long they stay on the home page. Please change the heading to "Work the Polls! (Super Tuesday March 5th; Early Voting February 20th - March 1st)".
Actually, does the banner move automatically or do you have to click on the arrow to get to the next banner item? Regardless, please put the new addition in the first position.ThanksHarriet
    On Sunday, February 18, 2024 at 06:58:59 PM CST, Michael Brand ***@***.***> wrote:  
 
 


@hwasserstrum ,

I've made the image switch. Let me know what you think.

I would recommend just including the priority of any new tasks in the affiliated Git issue.

**Comment by miketbrand** [comment]
The banner will move automatically even without user interaction.
The change has been made.

**Comment by hwasserstrum** [comment]
Thanks!
    On Monday, February 19, 2024 at 09:38:29 PM CST, Michael Brand ***@***.***> wrote:  
 
 


The banner will move automatically even without user interaction.
The change has been made.
