### ISSUE TITLE
New endorsement

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#110]
Please add this to the top of the list of Thought Leader endorsements:

photo:
![image](https://github.com/rcvfortexas/rcvfortexas/assets/88623190/b5ff3134-5d1d-4ca5-8386-0b5165a0affd)

name: Congressman Dan Crenshaw

Content: 
I'm a big fan of ranked choice voting for primary elections.

**Comment by dsgit215** [comment]
Complete - https://www.rcvfortexas.org/endorsements

**Comment by hwasserstrum** [comment]
Crenshaw is new so I moved him up as the first thought leader. Thanks for making it easy for me to make one minor tweak and get it done.
    On Monday, March 4, 2024 at 12:36:11 PM CST, Debbie Spalding ***@***.***> wrote:  
 
 


Complete - https://www.rcvfortexas.org/endorsements
