### ISSUE TITLE
Advocate for RCV under Take Action

### ISSUE THREAD

**Issue by dsgit215** [chrisflesher/rcvfortexas#113]
Email request from Joanne Richards:

From: Joanne Richards <joanne.richards@rcvfortexas.org>
Date: Sat, Jan 27, 2024 at 1:37 PM
Subject: RCVforTexas website addition

I would like to have added to our website under the Take Action tab at item called Advocate for RCV.
I am proposing (and several RCV folks have looked at this) to change Contact Elected Offices with Advocate for RCV.
Attached is an outline and content of the changes that would come under Advocate for RCV. 

[changes to RCVforTexas website 2024.01.16.docx](https://github.com/rcvfortexas/rcvfortexas/files/14290339/changes.to.RCVforTexas.website.2024.01.16.docx)

If this makes sense then if you could make these changes that would be much appreciated.
If it needs further explanation, don’t hesitate to aks.

Joanne Richards, Vice-Chair
[joanne.richards@rcvfortexas.org](mailto:joanne.richards@rcvfortexas.org)
512-825-4991

**Comment by UXPrime** [comment]
@dsgit215 
(https://rcvfortexas.nationbuilder.com/admin/sites/1/pages/1349/preview?browser_id=default&logged_in=0&theme_id=5dabb2094445ea66232bca7e)

**Comment by UXPrime** [comment]
@dsgit215 
(https://rcvfortexas.nationbuilder.com/admin/sites/1/pages/1349/preview?browser_id=default&logged_in=0&theme_id=5dabb2094445ea66232bca7e)

**Comment by dsgit215** [comment]
Hi @UXPrime, I'm having a hard time understanding the content source document that was provided with this request, so I'm not sure that I can provide good feedback on the web page you've put together.  I suggest you follow-up with Joanne Richards to see if this aligns with what she was looking for.  

Beyond that, my only suggestion at this point is that you have the various reference links open in a new tab.

**Comment by UXPrime** [comment]
The 'Advocate for RCV' page was approved and is live (published).  - issue completed/closed.
The 'Contact Elected Officials' has been unpublished and is only visible to admin.  -  issue completed/closed. 



@miketbrand @dsgit215 how do I move this page up in the Take Action drop down menu? I have been looking for a way to do this. Is it reliant on coding or is there a feature that allows me to move this sub-page up or down?

**Comment by dsgit215** [comment]
Via the 'sub nav pages' tab under Take Action - https://rcvfortexas.nationbuilder.com/admin/sites/1/pages/87/subpages_nav
