### ISSUE TITLE
New recommended RCV application

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#114]
On our resources page instead of "RankedVote: Test Out RCV" please suggest using RCV123. You can get the links to that at RCV123.org.

**Comment by dsgit215** [comment]
RankedVote has been replaced with RCV123 on the Resources page.  @hwasserstrum - An additional instance of RankedVote is currently being used in the home page carousel. (See image below.)  Should this remain in place or removed?

![image](https://github.com/rcvfortexas/rcvfortexas/assets/77990608/a0313a71-ec17-43a7-a7eb-9d81b9d5dcc2)

**Comment by hwasserstrum** [comment]
The home page use of RankedVote is fine. We just want to let supporters know to use RCV123 for polls they may want to create going forward.Thanks!
    On Monday, March 4, 2024 at 01:37:02 PM CST, Debbie Spalding ***@***.***> wrote:  
 
 


RankedVote has been replaced with RCV123 on the Resources page. @hwasserstrum - An additional instance of RankedVote is currently being used in the home page carousel. (See image below.) Should this remain in place or removed?

image.png (view on web)
