### ISSUE TITLE
Add David Comeaux to Leadership Page

### ISSUE THREAD

**Issue by loraschafer** [chrisflesher/rcvfortexas#125]
[David Comeaux Bio.docx](https://github.com/user-attachments/files/15916665/David.Comeaux.Bio.docx)
![David Comeaux LinkedIn photo](https://github.com/rcvfortexas/rcvfortexas/assets/123136540/743f5064-d2c9-4418-bd5e-44ac398615a3)

Title: Chair

**Comment by miketbrand** [comment]
David Comeaux has been added to the leadership page.
