### ISSUE TITLE
Search for your Rep broken link

### ISSUE THREAD

**Issue by loraschafer** [chrisflesher/rcvfortexas#132]
link to search seems broken. User can input address, but clicking search it is saying "something is wrong, try again". 

https://www.irvfortexas.org/contact_elected_official

Please fix link.

**Comment by miketbrand** [comment]
The long story short is that our API key has expired.

First, a bit of context:
- The relevant file can be found in our Dropbox at the following file address: \nb_sync\rcvfortexas\sites\irvhome-2\contact_elected_official.html
- The code works by issuing an API request to a Google API that is is designed for this purpose:
```
function getRepresentativeInfoByAddress(address) {
    $('#getRepresentative').prop('disabled',true);
    $('.errors').hide();
    // This api key has a restricted set of HTTP referrers.
    // Check with Irene Foelschow if you need it updated.
    var apiKey = '***************-_*******************R55g';
    var endpoint = 'https://www.googleapis.com/civicinfo/v2/representatives';
    var representativeRequest = encodeURI(endpoint + '?key=' + apiKey + '&address=' + address);
    $.get(representativeRequest, handleResponse).fail(handleFailure);
}
```
- Google has more information on how this API works.  You can find it here: [https://developers.google.com/civic-information/docs/v2/representatives/representativeInfoByAddress](https://developers.google.com/civic-information/docs/v2/representatives/representativeInfoByAddress).  You can also test it by sending API requests directly to the API endpoint from the page at the link.

I've captured and examined a few of the API requests using a Burp Suite proxy.  It seems that the the API works fine when I use the temporary API key that is provided with the webpage above, but when I swap in our API key, I get the following response:
```
{
  "error": {
    "code": 403,
    "message": "Requests from referer https://explorer.apis.google.com are blocked.",
    "errors": [
      {
        "message": "Requests from referer https://explorer.apis.google.com are blocked.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_HTTP_REFERRER_BLOCKED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "civicinfo.googleapis.com",
          "consumer": "projects/1065125765711"
        }
      }
    ]
  }
}
```

Based on this, I'm fairly confident that if we just renew the API key, we'll be able to get it back up and running.  I just need to figure out how to do that.

**Comment by miketbrand** [comment]
It looks like I'll need to use the API Console via a Google account to generate a new API key, but I want to use an enterprise account to do it; both for the sake of posterity and because it stands to reason that's where the old API key was generated and still resides.  @loraschafer, can you provide the credentials for the executive account?  Please don't do it here, obviously, but if you see this, please reach out to me over text or phone to provide them.  I tried using the credentials that I already have to log in and was told that they changed 48 days ago.

**Comment by miketbrand** [comment]
The API key has been replaced and the search functionality has been tested.

**Comment by loraschafer** [comment]
Thank you!
