### ISSUE TITLE
What happened to the [info@rcvforrtexas.org](mailto:info@rcvforrtexas.org) email?

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#64]
We used to receive messages sent to [info@rcvfortexas.org](mailto:info@rcvfortexas.org). I could see those messages by going to Communication and viewing activity. Now the sender gets an "Address not found" message: Your message wasn't delivered to [info@rcvfortexas.org](mailto:info@rcvfortexas.org) because the address couldn't be found, or is unable to receive mail. The last messages we received were all sent through Twitter and I have no idea how that happens. I have to go back several months to find a message that was sent to [info@rvfortexas.org](mailto:info@rvfortexas.org). I don't know what changed. 
It would be nice to be able to give people an email address that works.

**Comment by chrisflesher** [comment]
I think this must have happened when we set up the GMail stuff through Google. I am guessing before someone had set up our e-mail through NationBuilder before and this got messed up whenever we made the switch. Set up a new info@rcvfortexas.org account through GMail today and will ask NationBuilder how to re-enable this.

Here is some related info:
https://support.nationbuilder.com/en/articles/2343720-benefits-of-receiving-email-in-your-nation#:~:text=If%20you'd%20like%20to,Team%20can%20finish%20the%20setup.

**Comment by chrisflesher** [comment]
This link seems to have the fix:
https://support.nationbuilder.com/en/articles/2343596-forward-email-to-a-broadcaster

**Comment by hwasserstrum** [comment]
So someone will be assigned to fix it? That would be great.ThanksHarriet
    On Saturday, February 12, 2022, 03:21:00 PM CST, chrisflesher ***@***.***> wrote:  
 
 


This link seems to have the fix:
https://support.nationbuilder.com/en/articles/2343596-forward-email-to-a-broadcaster

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chrisflesher** [comment]
This is working again now. Verified that messages sent to info@rcvfortexas.org show up in the communications dashboard.
