### ISSUE TITLE
Import CSV file

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#66]
Please import all of the voting districts for these 938 records
[harriet (1).csv](https://github.com/rcvfortexas/rcvfortexas/files/8109807/harriet.1.csv).
Please prioritize this task.
Thanks
Harriet

**Comment by chrisflesher** [comment]
@alexkarjeker or @ironunicorn would you be interested in looking at this?

**Comment by alexkarjeker** [comment]
@chrisflesher - I can work on it ahead of Sunday's meeting.

**Comment by hwasserstrum** [comment]
That would be great. Thanks!
    On Tuesday, February 22, 2022, 04:18:43 PM CST, alexkarjeker ***@***.***> wrote:  
 
 


@chrisflesher - I can work on it ahead of Sunday's meeting.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alexkarjeker** [comment]
Chatted with Chris and it seems like the districts are automatically in NB. Closing this task.

**Comment by hwasserstrum** [comment]
I am traveling so can’t confirm it, but I think that is a new feature of NB or one we recently turned on. Good to know it will happen automatically going forward. Saved you some work!
Thanks
Harriet
