### ISSUE TITLE
Supporters page

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#68]
Please create a page similar to this one on FairVote Minnesota's website: https://fairvotemn.org/mnsupporters.

At this time we only want to list these organizations:
R Street
Common Cause - Texas
Veterans for Political Innovation
League of Women Voters - Texas

Logos for each organization are attached. I'd also like to include supporting statements shown here: 
(https://docs.google.com/spreadsheets/d/1ICBSCoFd4xhxQqMe3xLoyuIG5v53U_g7/edit#gid=631681362).

![logo - Common Cause Texas](https://user-images.githubusercontent.com/88623190/155532424-452d2cb4-7f1e-4f06-b070-930f5a1ab992.svg)
![logo - League of Women Voters Texas](https://user-images.githubusercontent.com/88623190/155532456-b9134504-909c-4725-a0ad-4c188c43f8af.png)
![logo- R Street](https://user-images.githubusercontent.com/88623190/155530908-18b3fb5f-b943-4a9f-9927-ade502034030.png)
![logo- Veterans for Political Action](https://user-images.githubusercontent.com/88623190/155530917-543c1bb4-1aea-4080-bafe-0133e055e793.png)

**Comment by dsgit215** [comment]
UPDATE:  Ok @chrisflesher, I saw the invite and accepted it.  This item is now assigned to me.

_@chrisflesher - I'm still unable to assign the issue to myself._  

I'll take this.  My availability is spotty over the next several days, but I anticipate getting started soon.

**Comment by dsgit215** [comment]
@chrisflesher, @hwasserstrum - A preview of the page can be viewed[ here](https://rcvfortexas.nationbuilder.com/admin/sites/1/pages/127/preview?browser_id=default&logged_in=0&theme_id=5dabb2094445ea66232bca7e).  If you're unable to access this link, you can find the page, 'Supporters', in Nationbuilder in the sub-pages of 'About Us.'  Note: When the page is published, it's currently designated to fall in the third sub-nav position, just above 'Contact Us.'

If you have any content updates or presentation ideas to discuss, let me know.  Or if this works as is, let me know and I will publish it.   - Debbie

**Comment by chrisflesher** [comment]
Looks good to me! What do you think @hwasserstrum?

**Comment by hwasserstrum** [comment]
Page looks great other than the fact that the Veterans logo didn't show up. Then we are set to go. We already have a couple of additions to the endorsements. Do we keep this item open or open a new one?ThanksHarriet
    On Friday, March 4, 2022, 09:54:50 PM CST, Debbie Spalding ***@***.***> wrote:  
 
 


@chrisflesher, @hwasserstrum - A preview of the page can be viewed here. If you're unable to access this link, you can find the page, 'Supporters', in Nationbuilder in the sub-pages of 'About Us.' Note: When the page is published, it's currently designated to fall in the third sub-nav position, just above 'Contact Us.'

If you have any content updates or presentation ideas to discuss, let me know. Or if this works as is, let me know and I will publish it. - Debbie

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dsgit215** [comment]
I've re-inserted the Veterans logo and published the [page ](https://www.rcvfortexas.org/supporters ) with the current supporter listing.  I'll close this issue and @hwasserstrum - when you have additions, you can open a new issue.  - Debbie

**Comment by hwasserstrum** [comment]
Looks great. Thanks!
    On Saturday, March 19, 2022, 01:36:58 PM CDT, Debbie Spalding ***@***.***> wrote:  
 
 


I've re-inserted the Veterans logo and published the page  with the current supporter listing. I'll close this issue and @hwasserstrum - when you have additions, you can open a new issue. - Debbie

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
