### ISSUE TITLE
Supporters/Endorsements page

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#72]
Please change the name of the page to Endorsements.

Please divide the page into two sections: the top for Organizations; the bottom for Thought Leaders (unless you can think of a better way to distinguish the two!). The last two on this list are Thought Leaders; the top three are organizations with links to their logos.

Here are more to add:
Unite America believes that instant runoff voting (RCV) solves real problems facing Texas. The reform can save Texas taxpayer money, give Texas cities control over their own elections, ensure that all military votes are counted, and eliminate low-turnout primary runoffs that very few Texas voters participate in. The reform makes elections better, faster, and cheaper while guaranteeing majority rule — it's a common-sense reform for Texas to consider.

![image](https://user-images.githubusercontent.com/88623190/159787240-f5dd79ec-b9d1-4b50-9216-0d270e6266a8.png)

RepresentWomen’s mission is to strengthen our democracy by advancing reforms like ranked choice voting that break down barriers to ensure more women run, win, serve, and lead. Our 2016 and 2020 reports found that electoral outcomes for women and people of color are overall better in jurisdictions that have implemented ranked choice voting.

![Represent Women Logo Dark Tagline  (1)](https://user-images.githubusercontent.com/88623190/159786898-5a448a14-1e31-4d95-9b87-4c6ed2d50801.png)

Texas Civil Rights Project is a supporter of ranked choice voting because of its proven ability to ensure that election results genuinely reflect the will of the people. Ranked-choice voting alleviates several issues in our electoral system including vote-splitting, negative campaigning, and hyper-polarization. With ranked-choice voting we can make substantial progress toward building a true democracy for all.

![image](https://user-images.githubusercontent.com/88623190/159787476-896d78c5-f3a3-42e9-bbcd-856ddc2db855.png)

Conventional wisdom might suggest that it's mostly progressives that favor ranked choice voting, but in fact support for RCV is growing elsewhere on the political spectrum. The Republican Party used RCV to pick leaders in hotly contested races for Congress in Utah, governor in Virginia, and attorney general in Indiana. Fundamentally, ranked choice voting doesn't preference either party. RCV offers state parties across the country a way to make sure the most electable candidate emerges from primary elections, and a way to legislate more effectively by yielding political institutions better geared to bargaining and accommodation. This is a policy arena worth the serious attention of conservatives.
 -- Yuval Levin, American Enterprise Institute

I avidly support ranked choice voting, and you should feel free to use my name however it might be helpful.
 -- Sanford V Levinson, Professor of Government, University of Texas at Austin School of Law

**Comment by dsgit215** [comment]
I should be able to get to this within the next several days.

**Comment by dsgit215** [comment]
@hwasserstrum - The updates have been made and published. You can take a look [here](https://www.rcvfortexas.org/endorsements).  Let me know if you'd like the organizations to be re-ordered in any particular way or  if you see anything else that needs adjusting.  - Debbie

**Comment by hwasserstrum** [comment]
Looks great!ThanksHarriet
    On Friday, April 1, 2022, 02:03:20 PM CDT, Debbie Spalding ***@***.***> wrote:  
 
 


@hwasserstrum - The updates have been made and published. You can take a look here. Let me know if you'd like the organizations to be re-ordered in any particular way or if you see anything else that needs adjusting. - Debbie
