### ISSUE TITLE
Another endorsement; tighten existing page

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#73]
New endorsement:
There are cost savings and other advantages of instant runoffs. For example, it gets rid of the incentive for the opposition to fund a candidate to take a few percent from a nominee and allow the opposition to win even in a district where a majority oppose them. There is a role instant runoffs can play as part of election integrity. For example, Utah has done a great job of adopting instant runoffs while implementing safeguards like cleaning up voter lists and verifying each voter. With their reforms, every voter can be confident that elections can be transparent and secure and that their voice is heard.
John Pudner, Take Back Action Fund
![image](https://user-images.githubusercontent.com/88623190/164916973-b2c9f8a6-a2a8-4be8-9867-870b0857f1e9.png)

Please remove some of the extra white space between endorsements.
Thanks
Harriet

**Comment by dsgit215** [comment]
I should be able to get to this within the next week.

**Comment by hwasserstrum** [comment]
Thanks!
    On Wednesday, April 27, 2022, 07:49:26 PM CDT, Debbie Spalding ***@***.***> wrote:  
 
 


I should be able to get to this within the next week.

**Comment by dsgit215** [comment]
Updates complete - [https://www.rcvfortexas.org/endorsements](https://www.rcvfortexas.org/endorsements).  With regard to the white space, the varying logo dimensions make this a little difficult and some breathing room is a good thing.  Nonetheless, I've tightened it up a little bit.  Take a look and if it works for you, let me know, and I'll close this item.

**Comment by hwasserstrum** [comment]
It works. Thanks!
    On Tuesday, May 3, 2022, 01:01:31 PM CDT, Debbie Spalding ***@***.***> wrote:  
 
 


Updates complete - https://www.rcvfortexas.org/endorsements. With regard to the white space, the varying logo dimensions make this a little difficult and some breathing room is a good thing. Nonetheless, I've tightened it up a little bit. Take a look and if it works for you, let me know, and I'll close this item.
