### ISSUE TITLE
Contact Us form is broken

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#74]
I just sent a couple of test messages and the notification I receive does not include the text of the messages.

**Comment by dsgit215** [comment]
As you saw in your email, I've been playing with this.  I suspect that when you were testing it, the email that seemed to have missing message content was actually the confirmation email that the sender receives after submitting their message.  You should have also received an email with the actual message content --- like the one you received when I sent a test message.  

I'm going to assume it's working, but if you continue to find you're not getting the inbound message content, we can look into it further.  In the meantime, the last inbound message I see - prior to the testing by you and me - was from Micki Levine.  It came in approximately 2 months ago.  Did you receive that one?  It was something about google ads.

**Comment by hwasserstrum** [comment]
No, I didn't see that message which I now saw by looking up Micki Levine. Where can I see all messages sent?
    On Tuesday, May 3, 2022, 01:33:47 PM CDT, Debbie Spalding ***@***.***> wrote:  
 
 


As you saw in your email, I've been playing with this. I suspect that when you were testing it, the email that seemed to have missing message content was actually the confirmation email that the sender receives after submitting their message. You should have also received an email with the actual message content --- like the one you received when I sent a test message.

I'm going to assume it's working, but if you continue to find you're not getting the inbound message content, we can look into it further. In the meantime, the last inbound message I see - prior to the testing by you and me - was from Micki Levine. It came in approximately 2 months ago. Did you receive that one? It was something about google ads.

**Comment by dsgit215** [comment]
You can see the messages submitted on the Dashboard for the Contact Us page - [https://rcvfortexas.nationbuilder.com/admin/sites/1/pages/37/activities](https://rcvfortexas.nationbuilder.com/admin/sites/1/pages/37/activities ).  Scroll to the lower portion of the page.
