### ISSUE TITLE
Data project on bad emails

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#75]
If there is a phone number for any profile with a bad email address, text the person with this message: You signed up on the Ranked Choice Voting for Texas website and we would like to be able to send you action alerts and newsletters but there is a problem with your email address. Please text us a good address. Thanks.

**Comment by ghost** [comment]
I can take care of this. Using the filter of "any email address is bad" and "mobile number exists: yes," there are 30 people in NationBuilder that I can text. However, a couple of people here have opted out of texts. Should I still reach out to them?

**Comment by hwasserstrum** [comment]
I think we should respect their request of no texts. Can you please either call those two individuals yourself or send me the names and I will do so. 
The text message should thank them for signing up on our website to show their support for ranked choice voting. We hope to get a good email address so we can contact them at appropriate times when we want them to contact their Texas legislators and ask them to vote for a specific RCV bill. 
Thanks
Harriet

**Comment by ghost** [comment]
Understood.

**Comment by ghost** [comment]
All texts/calls have been sent to the people listed on the "Bad Email" page of the "NB People" spreadsheet on Google Drive. This is where the new emails, should I receive them, will be placed for admins to view and then edit in NB. Some of the emails, highlighted in yellow, may have simply been mistyped at registration and could be easily modified to make them valid addresses.

**Comment by ghost** [comment]
Someone replied to ask whether their email will be at risk of being sold to (or in other ways obtained by) other movements or campaigns if they update it in our database. What should the response be to this?

**Comment by hwasserstrum** [comment]
We do not share contact information with anyone or any other organization. We use your email address to keep you informed about the progress of our efforts and, most importantly, to be able to contact you when we want our supporters to reach out to their elected officials and ask them to vote for a bill. Sometimes we ask all supporters to contact their elected officials. Sometimes we reach out only to constituents of specific legislators we are targeting at that time. We always appreciate your support.

**Comment by ghost** [comment]
I haven't received any other updated emails in a while. Shall I ask those who haven't updated again since it has been over a month now or should this be marked as complete?

**Comment by chrisflesher** [comment]
Harriet it's currently in the hospital and may not reply. Seems like you'd
know better if it's worth sending another one but to me seems like the task
is complete.

**Comment by ghost** [comment]
I am so sorry to hear that, and I hope she is doing well. I'll review my spreadsheet again and decide.

**Comment by hwasserstrum** [comment]
thanks!
    On Saturday, September 3, 2022 at 02:40:15 PM CDT, austinbegin ***@***.***> wrote:  
 
 


I am so sorry to hear that, and I hope she is doing well. I'll review my spreadsheet again and decide.
