### ISSUE TITLE
Figure out how to edit tricked out home page

### ISSUE THREAD

**Issue by loraschafer** [chrisflesher/rcvfortexas#76]

**Comment by dsgit215** [comment]
@loraschafer - I'm able to access the edit function.  What needs to be done?

**Comment by loraschafer** [comment]
Debbie,
Would we be able to add the latest "Action Alert" and Newsletter blog post
to the "News" section on the header of the main page?
This seems like a coding fix, it doesn't seem to be available in the
generic template of the website.
Thank you,


Lora Schafer
817.657.6921

**Comment by dsgit215** [comment]
I can give it a try later today/tomorrow.  I'm not much of a coder, but I
might be able to figure it out.  In the meantime, would you please send me
a link to or an email of the specific content you want?  - Debbie

**Comment by loraschafer** [comment]
Action Alert: https://www.rcvfortexas.org/action_alert_now
Newsletter Blog: https://www.rcvfortexas.org/newletter_blog

Currently the News box only includes the most current upcoming event.
Harriet would like it to do the same for the "Action Alerts" and
"Newsletter blog if possible.

Thank you for working on this.

Lora Schafer
817.657.6921

**Comment by dsgit215** [comment]
As you suspected editing the 'News' section in the upper right of the homepage requires coding skills and access to the custom template files..***  As a workaround, I have used the Nationbuilder Featured Content Slider to feature these two items.  Kinda clunky (and doesn't translate really well to mobile), but perhaps it's better than nothing???  Take a look at the [home page ](https://www.rcvfortexas.org/) and let me know if this works.  

***See the [website documentation](https://docs.google.com/document/d/1Qeg8aErcbe6ZuRl9fH2fPNDpQ7b-LSoS/edit?usp=sharing&ouid=112217128832105126232&rtpof=true&sd=true)  on the Google Drive for more information about the custom template, Dropbox, etc.
