### ISSUE TITLE
Voting Districts

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#83]
Is there a way to go through the entire database and for each profile that has an address see if there are correct state upper and state lower districts. We supposedly have Auto districting turned on and NB has access to current district definitions. I'd first review a report of profiles where districts need to be added or corrections need to be made before inserting the correct district numbers.

**Comment by miketbrand** [comment]
Any easily identifiable corrections that need to be made are already made automatically by [NB's auto-districting feature](https://support.nationbuilder.com/en/articles/3296866-how-auto-districting-works).  The article even warns that any manually entered voting district information is likely to be over-written by the auto-districting algorithm.
