### ISSUE TITLE
Welcome Message to Direct Adds (P1)

### ISSUE THREAD

**Issue by miketbrand** [chrisflesher/rcvfortexas#85]
Welcome messages now only get sent to people who sign up directly on the website but not to people who we add based on sign-up sheets.

**Comment by UXPrime** [comment]
@miketbrand This may be a little over the top, but we can always streamline it.

Hi *Name*, 

Welcome to Ranked Choice Voting for Texas! We're excited to have you on board as one of our valued volunteers! To learn more about us, our goals and upcoming events in Texas, explore our website [here.](http://www.rcvfortexas.org/). We will contact you  you soon to get you started.

Let's go Texas!

Ranked Choice Voting for Texas
http://www.rcvfortexas.org/

**Comment by hwasserstrum** [comment]
Here is a suggested welcome message which was, I think, modeled after the welcome message sent to people who sign up on our website:

Thank you for your interest in Ranked Choice Voting for Texas. Are you ready to get involved?
   Sign up on our volunteer page (link to https://www.rcvfortexas.org/volunteer)
   Check out upcoming events (link to https://www.rcvfortexas.org/calendar_2)
   Donate to our efforts (link to https://www.rcvfortexas.org/donate)
   Host a RCV house party (link to https://docs.google.com/forms/d/1NzGG9kTXw34zFhhiXniBNTGaNBLmwGIwG6jo2UzBYSk/edit) -- note: we need to figure out when we get a form submitted

Want to learn more about Ranked Choice Voting (a.k.a. Instant Runoff Voting)? 
   What is Ranked Choice / Instant Runoff Voting? (link to https://www.rcvfortexas.org/what_is_rcv)
   Why Adopt Ranked Choice Voting? (link to https://www.rcvfortexas.org/why_adopt_rcv)                    
   Where in Texas is RCV used today? (link to https://www.rcvfortexas.org/where_in_texas)

Tell your friends about RCV! Follow and share on social media (list each with links to our Facebook, Instagram, Twitter and LinkedIn pages. Visit our website at http://www.rcvfortexas.org./

Are there groups or organizations you belong to or know of who may want to learn more about RCV? We would be happy to present to them and invite their support. Contact us (link to info@rcvfortexas.org)

We look forward to staying in touch!

Ranked Choice Voting for Texas
http://www.rcvfortexas.org/

**Comment by miketbrand** [comment]
This issue has been determined to be a priority 1 (high priority) issue.

**Comment by UXPrime** [comment]
_Sorry for the prolonged wait._

**Revision:** 

Welcome to Ranked Choice Voting for Texas! We're excited that you are interested to learn more about what we do! Are you ready to help us make our voting system more cost effective and efficient? So are we, and we will contact you soon to get things started.

Meanwhile, why not learn more about us and explore our website [here]((http://www.rcvfortexas.org.) 
Check out upcoming [events](https://www.rcvfortexas.org/calendar_2) 
Contribute to our mission to make rank choice voting official with your [donations](https://www.rcvfortexas.org/donate). 
You can sign up to host a [RCV House Party](https://docs.google.com/forms/d/1NzGG9kTXw34zFhhiXniBNTGaNBLmwGIwG6jo2UzBYSk/edit) and get people on board! 

Learn more about Ranked Choice Voting (a.k.a. Instant Runoff Voting).
[What is Ranked Choice / Instant Runoff Voting?](https://www.rcvfortexas.org/what_is_rcv) 
[Why Adopt Ranked Choice Voting?](https://www.rcvfortexas.org/why_adopt_rcv) 
[Where in Texas is RCV used today? ](https://www.rcvfortexas.org/where_in_texas)

Tell your friends about RCV! Follow and share on social media 

[Facebook](https://www.facebook.com/rcvfortx/)
[Instagram](https://www.instagram.com/rcvfortx/) 
[X](https://twitter.com/RcvTx) 
[LinkedIn]( https://www.linkedin.com/company/ranked-choice-voting-for-texas/)
[Website](http://www.rcvfortexas.org./) 
[Email](info@rcvfortexas.org) 

If you know of, or belong to any groups or organizations that may want to learn more about RCV, let us know. We would love to meet with them and invite their support or have them contact us at info@rcvfortexas.org

Thank you for choosing to help us make Rank Choice Voting a reality. 

Let's go Texas!
[Rank Choice Voting for Texas](http://www.rcvfortexas.org/)

**Comment by miketbrand** [comment]
I love this message!

One point that Debbie has pointed out is that the first line of the message says that the recipient is a "valued volunteer".  Direct adds aren't just volunteers, though.  In most cases, it's just folks that signed the clipboard for us when we went canvassing.

We'll need to workshop the wording there, but otherwise, this is phenomenal!

**Comment by hwasserstrum** [comment]
I think that just the August 19th draft said "valued volunteer"; the revision does not. I don't know why there are links to "website" and "email" at the bottom of the message.

**Comment by UXPrime** [comment]
1. The multiple source automation set up is in progress. Will inform when complete, shortly. - **Completed.**
2. A test email was sent to @miketbrand and @hwasserstrum. 
3. @hwasserstrum I made the edits you suggested after sending the test email. The changes were updated in the template after.
4. I selected a basic email template that can include the logo. You can however change this and adjust as is best suited for the RCV brand. 

- The email has been set up. The name of the email template is a test name (to be changed according to your preference). I can show it during our next meeting however if you wish to check beforehand, the title in the workflow section is 'New Sign Ups (Manual)'. 
- I thought I could create a list for new sign ups in the people section and use that list to help auto-populate the template email address field. It seems however you have to manually enter them one at a time, you however can add multiple addresses in the single email. I was hoping the new names could simply be part of a specific 'people' list that you could select and then it would load it into the email and you simply press send. If anyone knows how to do this please let me know. I've been exploring the site to see if this was possible, but may have missed it somehow.

**Comment by hwasserstrum** [comment]
Sorry, I lost track of this. I too loved the changes Tanya suggested.  I don't know what "The multiple source automation set up is in progress" means. I just sent a version to David to review. He is going to insert his calendly information. There are two open items: 
1. I am redoing the volunteer page and that should be included. 
2. We shouldn't include a link to host a house party until we have a way to know when a form is submitted. 

I'd like two cosmetic changes:
1. Delete "more cost effective and efficient" and insert "better, faster, and cheaper"
2. I don't think we should expect someone who signs up to ask an organization to contact us. How about "We would love to meet with them and invite their support. Tell us about them at [info@rcvfortexas.org](mailto:info@rcvfortexas.org)"

I should be back soon with a new volunteer page, a decision about house parties, and David's calendly changes.
Thanks!

**Comment by UXPrime** [comment]
@hwasserstrum @miketbrand @
> _Sorry, I lost track of this. I too loved the changes Tanya suggested. I don't know what "The multiple source automation set up is in progress" means. I just sent a version to David to review. He is going to insert his calendly information. There are two open items:
> 
> 1. I am redoing the volunteer page and that should be included.
> 2. We shouldn't include a link to host a house party until we have a way to know when a form is submitted.
> 
> I'd like two cosmetic changes:
> 
> 1. Delete "more cost effective and efficient" and insert "better, faster, and cheaper"
> 2. I don't think we should expect someone who signs up to ask an organization to contact us. How about "We would love to meet with them and invite their support. Tell us about them at [info@rcvfortexas.org](mailto:info@rcvfortexas.org)"
> 
> I should be back soon with a new volunteer page, a decision about house parties, and David's Calendly changes. Thanks!_

**Revision 2:**

Welcome to Ranked Choice Voting for Texas! We're excited that you are interested to learn more about what we do! Are you ready to help us make our voting system better, faster, and cheaper? So are we, and we will contact you soon to get things started.

Meanwhile, why not learn more about us and explore our website [here]((http://www.rcvfortexas.org/.)
Check out upcoming [events](https://www.rcvfortexas.org/calendar_2)
Contribute to our mission to make rank choice voting official with your [donations](https://www.rcvfortexas.org/donate).
You can sign up to host a [RCV House Party](https://docs.google.com/forms/d/1NzGG9kTXw34zFhhiXniBNTGaNBLmwGIwG6jo2UzBYSk/edit) and get people on board!

Learn more about Ranked Choice Voting (a.k.a. Instant Runoff Voting).
[What is Ranked Choice / Instant Runoff Voting?](https://www.rcvfortexas.org/what_is_rcv)
[Why Adopt Ranked Choice Voting?](https://www.rcvfortexas.org/why_adopt_rcv)
[Where in Texas is RCV used today?](https://www.rcvfortexas.org/where_in_texas)

Tell your friends about RCV! Follow and share on social media

[Facebook](https://www.facebook.com/rcvfortx/)
[Instagram](https://www.instagram.com/rcvfortx/)
[X](https://twitter.com/RcvTx)
[LinkedIn](https://www.linkedin.com/company/ranked-choice-voting-for-texas/)
[Website](http://www.rcvfortexas.org./)
[Email](https://github.com/rcvfortexas/rcvfortexas/issues/info@rcvfortexas.org)

If you know of, or belong to any groups or organizations that may want to learn more about RCV, tell us about them at [info@rcvfortexas.org](mailto:info@rcvfortexas.org)

Thank you for choosing to help us make Rank Choice Voting a reality.

Let's go Texas!

**Comment by dsgit215** [comment]
@UXPrime - Hi Tanya,  Here's some information about how to insert the Communication Preferences link into an email (i.e. over and above the link that's currently in the email footer - https://support.nationbuilder.com/en/articles/2363000-how-to-run-a-re-permissioning-campaign#send-your-consent-form .

The specific consent form you would use is 'comm-pref-mgt-all-v1B'.  You can copy the liquid variable snippet from here - https://rcvfortexas.nationbuilder.com/admin/consent_forms.  

NOTE!!!
1.)  If/when Mike adds a consent subject for "Supporter", a new version of the form would need to be created.  Therefore, the new liquid variable associated with that form would need to be put in an updated version of the 'Welcome' message.
2.) Unfortunately, it's not possible to add a style to the liquid variable, so be aware that the link that it generates inside the email may have a different style from the other content in the email.  

If you have any questions, let me know.  

- Debbie

**Comment by miketbrand** [comment]
@UXPrime will add language to the body of the email prompting new users to update their communication preferences.
