### ISSUE TITLE
Make the Volunteer Page the Landing Page for New Sign-Ups

### ISSUE THREAD

**Issue by miketbrand** [chrisflesher/rcvfortexas#93]

**Comment by AceTylerCholine** [comment]
Currently after signing up on the page: **get-involved** page, people are forwarded to the **signup_thank_you** page.
Changed forward to **volunteer** page

**Comment by AceTylercholine** [comment]
Currently after signing up on the page: **get-involved** page, people are forwarded to the **signup_thank_you** page.
Changed forward to **volunteer** page

**Comment by dsgit215** [comment]
Because of changes made for https://github.com/rcvfortexas/rcvfortexas/issues/94, I updated the Volunteer page slug to the latest version.
