### ISSUE TITLE
Verify duplicates to merge or leave separate. Confirm with assigned sign up volunteers.

### ISSUE THREAD

**Issue by UXPrime** [chrisflesher/rcvfortexas#95]
- Go through potential duplicates, 
- Verify the names and if the information are overlaps, corrections or separate contacts. 
- Confirm the flagged contact entries with recruiters or point of contacts via Slack, or if permitted, email.

**Comment by miketbrand** [comment]
I spoke the Harriet about this.  She said that most recruiting efforts are attributed back to her, so contacting the recruiter won't do you much good.  She recommended to the recruit directly using the contact information given in NationBuilder and ask them if all of the potential duplicate is also them.

She also clarified that this should be a priority 2 (medium priority) issue.

**Comment by UXPrime** [comment]
This was completed. I found a way to confirm most of the them efficiently. Only one is left to date.  this includes the ones you recently imported. @miketbrand
